Added run query and tests for coupled contracts
synek317/subz pull request #5
Opened 2020-08-06 09:15 UTC by dwawrzyniak

2020-08-07 10:40 UTC, smwoj requested changes

2020-08-07 10:40 UTC, smwoj commented on subz_commands_aclr8.py
> +  from shutil import rmtree
I'd remove duplicate imports (copy_tree and rmtree) by moving them to the top level.

Also, is what's the reason for these try/except imports?  It seems to me only the dot-prefixed versions should work.

2020-08-07 10:40 UTC, smwoj commented on subz_commands_aclr8.py
> +class SubzAclr8QueryCoupled(sublime_plugin.WindowCommand):
there's a lot of duplication with `SubzAclr8TestsCoupled`. Would it be worth it to remove it, e.g. via inheritance?

2020-08-07 10:40 UTC, smwoj commented on subz_commands_aclr8.py
> +class SubzAclr8TestsCoupled(sublime_plugin.WindowCommand):
there are a few nitpicks, but maybe they would be best proposed together:
```python
class SubzAclr8TestsCoupled(sublime_plugin.WindowCommand):
  def run(self):
    view = sublime.active_window().active_view()

    if not ion_is_saved(view):
      sublime.message_dialog("Please save all changes before running tests")
      return

    file_path = view.file_name()
    working_dir, _fname = os.path.split(file_path)

    with ExitStack() as stack:
      if "coupled" not in working_dir:
        tmp_dir_root = stack.enter_context(TemporaryDirectory())
        tmp_dir = os.path.join(tmp_dir_root, "coupled")
        copy_tree(working_dir, tmp_dir)
        working_path = tmp_dir

      run_aclr8_command("test " + working_path + "/", on_success=lambda output: append_output_panel(output + "All tests passed."))


```
Using the `with` statement  (for scoped resources) allows removing the callbacks. What do you think?

(required imports
```
from contextlib import ExitStack
from tempfile import TemporaryDirectory
```
)

2020-08-07 12:24 UTC, smwoj approved these changes

2020-08-17 08:00 UTC, synek317 approved these changes

2020-08-17 08:00 UTC, merged